spring.application.name=api-gateway
server.port=8085

security.jwt.secret=TXlTdXBlclNlY3JldEtleUZvckF1dGhTZXJ2aWNlSldUMjAyNg==

rate-limit.auth.capacity=5
rate-limit.auth.refill-period-seconds=60
rate-limit.api.capacity=30
rate-limit.api.refill-period-seconds=60

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=event-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/events/**

spring.cloud.gateway.server.webflux.routes[2].id=reservation-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/reservations/**
