spring.application.name=reservation-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${RESERVATION_DB_NAME:reservation_service_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:Isabel1978}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${JWT_SECRET:TXlTdXBlclNlY3JldEtleUZvckF1dGhTZXJ2aWNlSldUMjAyNg==}

# REST clients
clients.event-service.base-url=${EVENT_SERVICE_URL:http://${EVENT_SERVICE_HOST:localhost}:${EVENT_SERVICE_PORT:8081}}

# Kafka base configuration
app.kafka.enabled=true
app.kafka.topics.user-registered=user.registered
app.kafka.topics.reservation-created=reservation.created
app.kafka.topics.payment-completed=payment.completed

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.consumer.group-id=reservation-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
